name: Deploy to GCP

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '340.0.0'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
        run: |
          printf ${{ secrets.GCP_SA_KEY }} > /tmp/gcp_sa_key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp_sa_key.json

      - name: Configure Docker credentials
        run: |
          printf ${{ secrets.GCR_AUTH_TOKEN }} | base64 --decode | docker login -u _json_key --password-stdin https://gcr.io

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/concrete-braid-392715/argo-ai:${{ github.sha }} .
          docker push gcr.io/concrete-braid-392715/argo-ai:${{ github.sha }}

      - name: Deploy to GCP
        run: |
          gcloud config set project concrete-braid-392715
          gcloud config set compute/zone <zone>
          gcloud container clusters get-credentials <cluster-name>
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
